debug:
  path: plugins/BungeePermsBukkit/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: bungeeperms
    mysqluser: bungeeperms
    mysqlpw: password
backendtype: YAML
uuidplayerdb: YAML
useUUIDs: false
allowops: false
servername: someserver