backendtype: YAML
debug:
  path: plugins/BungeePermsBukkit/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: bungeeperms
    mysqluser: bungeeperms
    mysqlpw: password
allowops: false
useUUIDs: false
uuidplayerdb: YAML